# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kb_indexer/kbapi/indexing.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'kb_indexer/kbapi/indexing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fkb_indexer/kbapi/indexing.proto\x12\x12webitel.kb.service\"9\n\x1cResolveSpaceEmbeddingRequest\x12\x19\n\x08space_id\x18\x01 \x01(\x03R\x07spaceId\"\x8b\x02\n\x0eSpaceEmbedding\x12\x32\n\x15vector_search_enabled\x18\x01 \x01(\x08R\x13vectorSearchEnabled\x12\x19\n\x08model_id\x18\x02 \x01(\x03R\x07modelId\x12\x1a\n\x08provider\x18\x03 \x01(\tR\x08provider\x12\x1b\n\tmodel_ref\x18\x04 \x01(\tR\x08modelRef\x12\x1e\n\ndimensions\x18\x05 \x01(\x05R\ndimensions\x12\x1a\n\x08\x65ndpoint\x18\x06 \x01(\tR\x08\x65ndpoint\x12\x17\n\x07\x61pi_key\x18\x07 \x01(\tR\x06\x61piKey\x12\x1c\n\tvalidated\x18\x08 \x01(\x08R\tvalidated2y\n\x08Indexing\x12m\n\x15ResolveSpaceEmbedding\x12\x30.webitel.kb.service.ResolveSpaceEmbeddingRequest\x1a\".webitel.kb.service.SpaceEmbeddingB8Z6github.com/webitel/webitel-kb/api/kb/service;servicepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kb_indexer.kbapi.indexing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/webitel/webitel-kb/api/kb/service;servicepb'
  _globals['_RESOLVESPACEEMBEDDINGREQUEST']._serialized_start=55
  _globals['_RESOLVESPACEEMBEDDINGREQUEST']._serialized_end=112
  _globals['_SPACEEMBEDDING']._serialized_start=115
  _globals['_SPACEEMBEDDING']._serialized_end=382
  _globals['_INDEXING']._serialized_start=384
  _globals['_INDEXING']._serialized_end=505
# @@protoc_insertion_point(module_scope)
