"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ResolveSpaceEmbeddingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPACE_ID_FIELD_NUMBER: _builtins.int
    space_id: _builtins.int
    def __init__(
        self,
        *,
        space_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["space_id", b"space_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolveSpaceEmbeddingRequest: _TypeAlias = ResolveSpaceEmbeddingRequest  # noqa: Y015

@_typing.final
class SpaceEmbedding(_message.Message):
    """SpaceEmbedding is what the worker needs to embed the chunks of a space."""

    DESCRIPTOR: _descriptor.Descriptor

    VECTOR_SEARCH_ENABLED_FIELD_NUMBER: _builtins.int
    MODEL_ID_FIELD_NUMBER: _builtins.int
    PROVIDER_FIELD_NUMBER: _builtins.int
    MODEL_REF_FIELD_NUMBER: _builtins.int
    DIMENSIONS_FIELD_NUMBER: _builtins.int
    ENDPOINT_FIELD_NUMBER: _builtins.int
    API_KEY_FIELD_NUMBER: _builtins.int
    VALIDATED_FIELD_NUMBER: _builtins.int
    vector_search_enabled: _builtins.bool
    """False when the space is not embedded; every field below is then unset."""
    model_id: _builtins.int
    """Model the vectors are stored under (kb.chunk_embedding.model_id)."""
    provider: _builtins.str
    model_ref: _builtins.str
    dimensions: _builtins.int
    endpoint: _builtins.str
    """URL of a self-hosted service; empty for cloud providers."""
    api_key: _builtins.str
    """Provider credential in plaintext; empty for self-hosted providers."""
    validated: _builtins.bool
    """Registration test call result; reported, not enforced."""
    def __init__(
        self,
        *,
        vector_search_enabled: _builtins.bool = ...,
        model_id: _builtins.int = ...,
        provider: _builtins.str = ...,
        model_ref: _builtins.str = ...,
        dimensions: _builtins.int = ...,
        endpoint: _builtins.str = ...,
        api_key: _builtins.str = ...,
        validated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_key", b"api_key", "dimensions", b"dimensions", "endpoint", b"endpoint", "model_id", b"model_id", "model_ref", b"model_ref", "provider", b"provider", "validated", b"validated", "vector_search_enabled", b"vector_search_enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpaceEmbedding: _TypeAlias = SpaceEmbedding  # noqa: Y015
