"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from kb_indexer.kbapi import indexing_pb2 as _indexing_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class IndexingStub:
    """Indexing serves the knowledge base indexer worker. Service to service: no
    objclass, no HTTP bindings, a service token instead of a user session.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> IndexingAsyncStub: ...
    ResolveSpaceEmbedding: _grpc.UnaryUnaryMultiCallable[_indexing_pb2.ResolveSpaceEmbeddingRequest, _indexing_pb2.SpaceEmbedding]
    """ResolveSpaceEmbedding returns the embedding model of a space with its credential."""

@_typing.type_check_only
class IndexingAsyncStub(IndexingStub):
    """Indexing serves the knowledge base indexer worker. Service to service: no
    objclass, no HTTP bindings, a service token instead of a user session.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ResolveSpaceEmbedding: _aio.UnaryUnaryMultiCallable[_indexing_pb2.ResolveSpaceEmbeddingRequest, _indexing_pb2.SpaceEmbedding]  # type: ignore[assignment]
    """ResolveSpaceEmbedding returns the embedding model of a space with its credential."""

class IndexingServicer(metaclass=_abc_1.ABCMeta):
    """Indexing serves the knowledge base indexer worker. Service to service: no
    objclass, no HTTP bindings, a service token instead of a user session.
    """

    @_abc_1.abstractmethod
    def ResolveSpaceEmbedding(
        self,
        request: _indexing_pb2.ResolveSpaceEmbeddingRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_indexing_pb2.SpaceEmbedding, _abc.Awaitable[_indexing_pb2.SpaceEmbedding]]:
        """ResolveSpaceEmbedding returns the embedding model of a space with its credential."""

def add_IndexingServicer_to_server(servicer: IndexingServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
