# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kb_indexer.kbapi import indexing_pb2 as kb__indexer_dot_kbapi_dot_indexing__pb2


class IndexingStub:
    """Indexing serves the knowledge base indexer worker. Service to service: no
    objclass, no HTTP bindings, a service token instead of a user session.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveSpaceEmbedding = channel.unary_unary(
                '/webitel.kb.service.Indexing/ResolveSpaceEmbedding',
                request_serializer=kb__indexer_dot_kbapi_dot_indexing__pb2.ResolveSpaceEmbeddingRequest.SerializeToString,
                response_deserializer=kb__indexer_dot_kbapi_dot_indexing__pb2.SpaceEmbedding.FromString,
                _registered_method=True)


class IndexingServicer:
    """Indexing serves the knowledge base indexer worker. Service to service: no
    objclass, no HTTP bindings, a service token instead of a user session.
    """

    def ResolveSpaceEmbedding(self, request, context):
        """ResolveSpaceEmbedding returns the embedding model of a space with its credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveSpaceEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveSpaceEmbedding,
                    request_deserializer=kb__indexer_dot_kbapi_dot_indexing__pb2.ResolveSpaceEmbeddingRequest.FromString,
                    response_serializer=kb__indexer_dot_kbapi_dot_indexing__pb2.SpaceEmbedding.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webitel.kb.service.Indexing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('webitel.kb.service.Indexing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Indexing:
    """Indexing serves the knowledge base indexer worker. Service to service: no
    objclass, no HTTP bindings, a service token instead of a user session.
    """

    @staticmethod
    def ResolveSpaceEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/webitel.kb.service.Indexing/ResolveSpaceEmbedding',
            kb__indexer_dot_kbapi_dot_indexing__pb2.ResolveSpaceEmbeddingRequest.SerializeToString,
            kb__indexer_dot_kbapi_dot_indexing__pb2.SpaceEmbedding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
